[package]
name = "muzanci-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
git2 = "0.21.0"
serde = "1.0.229"
muzanci-interpreter = { path = "../muzanci-interpreter" }
muzanci-transport = { path = "../muzanci-transport" }
muzanci-git = { path = "../muzanci-git" }
url = "2.5.8"
tokio = { version = "1.53.1", features = ["io-std", "rt-multi-thread"] }
reqwest = "0.13.4"
tokio-util = "0.7.19"
hyper = "1.11.0"
hyper-util = "0.1.20"
http = "1.5.0"
http-body-util = "0.1.4"
bytes = "1.12.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2.5"
thiserror = "2.0.20"
tracing-error = "0.2.1"
async-trait = "0.1.92"
russh = "0.62.6"
russh-keys = "0.49.2"
crossterm = "0.29.0"
nix = { version = "0.31.3", features = ["fs", "term"] }

[lib]
name = "muzanci_cli"
path = "src/lib.rs"

[[bin]]
name = "muzanci-cli"
path = "src/main.rs"
